services:
    metadata.pass.translation:
        class: Innmid\AppBundle\Graph\MetadataPass\TranslationPass
        calls:
            - ['setGraph', ['@graph']]
        tags:
            - { name: graph.metadata }
