services:
    metadata.pass:
        abstract: true
        calls:
            - ['setGraph', ['@graph']]

    metadata.pass.translation:
        class: Innmind\AppBundle\Graph\MetadataPass\TranslationPass
        parent: metadata.pass
        tags:
            - { name: graph.metadata }

    metadata.pass.abbreviation:
        class: Innmind\AppBundle\Graph\MetadataPass\AbbreviationPass
        parent: metadata.pass
        tags:
            - { name: graph.metadata }

    metadata.pass.citation:
        class: Innmind\AppBundle\Graph\MetadataPass\CitationPass
        parent: metadata.pass
        tags:
            - { name: graph.metadata }

    metadata.pass.host:
        class: Innmind\AppBundle\Graph\MetadataPass\HostPass
        parent: metadata.pass
        tags:
            - { name: graph.metadata }

    metadata.pass.canonical:
        class: Innmind\AppBundle\Graph\MetadataPass\CanonicalPass
        parent: metadata.pass
        tags:
            - { name: graph.metadata }
