api_node_get:
    path:     /api/node/{uuid}
    defaults: { _controller: InnmindAppBundle:API/Node:get }
    requirements:
        uuid: '\w{8}-(\w{4}-){3}\w{12}'
    methods: [GET]
    condition: "request.headers.get('Accept') === 'application/vnd.innmind.v1+json'"

api_node_create:
    path:     /api/node/
    defaults: { _controller: InnmindAppBundle:API/Node:create }
    methods: [POST]
    condition: "request.headers.has('X-Token') and request.headers.has('X-Resource') and request.headers.get('Accept') === 'application/vnd.innmind.v1+json'"

api_node_update:
    path:     /api/node/{uuid}
    defaults: { _controller: InnmindAppBundle:API/Node:update }
    requirements:
        uuid: '\w{8}-(\w{4}-){3}\w{12}'
    methods: [PUT]
    condition: "request.headers.has('X-Token') and request.headers.has('X-Resource') and request.headers.get('Accept') === 'application/vnd.innmind.v1+json'"

api_info:
    path: /api/info
    defaults: { _controller: InnmindAppBundle:API/Info:index }
    methods: [GET]
    condition: "request.headers.get('Accept') === 'application/json'"
