api_node_get:
    path:     /api/node/{uuid}
    defaults: { _controller: InnmindAppBundle:API/Node:get }
    requirements:
        uuid: '\w{8}-(\w{4}-){3}\w{12}'
    methods: [GET]

api_node_create:
    path:     /api/node/
    defaults: { _controller: InnmindAppBundle:API/Node:create }
    methods: [POST]
    condition: "request.headers.has('X-Token') and request.headers.has('X-Resource')"

api_node_update:
    path:     /api/node/{uuid}
    defaults: { _controller: InnmindAppBundle:API/Node:update }
    requirements:
        uuid: '\w{8}-(\w{4}-){3}\w{12}'
    methods: [PUT]
    condition: "request.headers.has('X-Token') and request.headers.has('X-Resource')"
