services:
    uuid:
        class: Innmind\AppBundle\UUID

    server.security.authentication.provider:
        class: Innmind\AppBundle\Security\Authentication\Provider\ServerProvider
        arguments: [""]

    server.security.authentication.listener:
        class: Innmind\AppBundle\Security\Firewall\ServerListener
        arguments: ["@security.context", "@security.authentication.manager"]

    server_provider:
        class: Innmind\AppBundle\Security\Server\ServerProvider
        calls:
            - ['setEntityManager', ['@doctrine.orm.entity_manager']]

    resource_token_provider:
        class: Innmind\AppBundle\Provider\ResourceTokenProvider
        calls:
            - ['setEntityManager', ['@doctrine.orm.entity_manager']]

    node.label_guesser:
        class: Innmind\AppBundle\LabelGuesser

    neo4j_client:
        class: Everyman\Neo4j\Client
        arguments: ['%neo4j_host%', '%neo4j_port%']

    graph:
        class: Innmind\AppBundle\Graph
        calls:
            - ['setClient', ['@neo4j_client']]
            - ['setGenerator', ['@uuid']]
            - ['setDispatcher', ['@event_dispatcher']]
            - ['setLogger', ['@logger']]

    node.normalizer:
        class: Innmind\AppBundle\Normalization\NodeNormalizer

    node.publisher:
        class: Innmind\AppBundle\Graph\NodePublisher
        calls:
            - ['setGraph', ['@graph']]
            - ['setLabelGuesser', ['@node.label_guesser']]
            - ['setMetadata', ['@graph.metadata']]

    api.hateoas:
        class: Innmind\AppBundle\API\Hateoas
        calls:
            - ['setGenerator', ['@router']]

    rabbit:
        class: Innmind\AppBundle\RabbitMQ

    graph.node.listener:
        class: Innmind\AppBundle\Listener\NodeEventListener
        calls:
            - ['setRabbit', ['@rabbit']]
            - ['setGenerator', ['@uuid']]
            - ['setEntityManager', ['@doctrine.orm.entity_manager']]
            - ['setGraph', ['@graph']]
            - ['setUrlGenerator', ['@router']]
            - ['setDomainParser', ['@domain_parser']]
        tags:
            - { name: kernel.event_listener, event: graph.node.post_create, method: onPostCreate }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate }

    graph.metadata:
        class: Innmind\AppBundle\Graph\Metadata

    domain_parser:
        class: Pdp\Parser
        factory_class: Innmind\AppBundle\DomainParserFactory
        factory_method: make

    http_client:
        class: GuzzleHttp\Client

    innmind_analyzer:
        class: Innmind\AppBundle\InnmindAnalyzer
        calls:
            - ['setHttpClient', ['@http_client']]
            - ['setUrlGenerator', ['@router']]
