services:
    uuid:
        class: Innmind\AppBundle\UUID

    server.security.authentication.provider:
        class: Innmind\AppBundle\Security\Authentication\Provider\ServerProvider
        arguments: [""]

    server.security.authentication.listener:
        class: Innmind\AppBundle\Security\Firewall\ServerListener
        arguments: ["@security.context", "@security.authentication.manager"]

    server_provider:
        class: Innmind\AppBundle\Security\Server\ServerProvider
        calls:
            - ['setEntityManager', ['@doctrine.orm.entity_manager']]

    resource_token_provider:
        class: Innmind\AppBundle\Provider\ResourceTokenProvider
        calls:
            - ['setEntityManager', ['@doctrine.orm.entity_manager']]

    node.label_guesser:
        class: Innmind\AppBundle\LabelGuesser

    neo4j_client:
        class: Everyman\Neo4j\Client
        arguments: ['%neo4j_host%', '%neo4j_port%']

    graph:
        class: Innmind\AppBundle\Graph
        calls:
            - ['setClient', ['@neo4j_client']]
            - ['setGenerator', ['@uuid']]
            - ['setDispatcher', ['@event_dispatcher']]

    node.normalizer:
        class: Innmind\AppBundle\Normalization\NodeNormalizer

    node.publisher:
        class: Innmind\AppBundle\Graph\NodePublisher
        calls:
            - ['setGraph', ['@graph']]
            - ['setLabelGuesser', ['@node.label_guesser']]

    api.hateoas:
        class: Innmind\AppBundle\API\Hateoas
        calls:
            - ['setGenerator', ['@router']]
