security:
    access_decision_manager:
        strategy: unanimous

    providers:
        server:
            id: server_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        publication:
            pattern: ^/api/publish.*
            stateless: true
            anonymous: ~
            server: true

        default:
            pattern: ^/
            stateless: true
            anonymous: ~

    access_control:
        - { path: ^/api/publish.*, roles: [ROLE_WORKER, ROLE_CRAWLER] }
